// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOf9C3fq-Cc3x-uaHrhjW6mE5AG76gu1I',
    appId: '1:1037529854701:web:9d103a9780f81390b052e4',
    messagingSenderId: '1037529854701',
    projectId: 'fcm1-e8c54',
    authDomain: 'fcm1-e8c54.firebaseapp.com',
    storageBucket: 'fcm1-e8c54.appspot.com',
    measurementId: 'G-BGQW5H4TQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF92aTeFD96S6aOcF83hqfoTySVU6YB0g',
    appId: '1:1037529854701:android:ab71877a0691a0b6b052e4',
    messagingSenderId: '1037529854701',
    projectId: 'fcm1-e8c54',
    storageBucket: 'fcm1-e8c54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHnp_324o8hQdwVekJ0ulT1yjur_zvlIo',
    appId: '1:1037529854701:ios:dc1f7de79f480db0b052e4',
    messagingSenderId: '1037529854701',
    projectId: 'fcm1-e8c54',
    storageBucket: 'fcm1-e8c54.appspot.com',
    iosBundleId: 'com.example.dkuCapstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHnp_324o8hQdwVekJ0ulT1yjur_zvlIo',
    appId: '1:1037529854701:ios:dc1f7de79f480db0b052e4',
    messagingSenderId: '1037529854701',
    projectId: 'fcm1-e8c54',
    storageBucket: 'fcm1-e8c54.appspot.com',
    iosBundleId: 'com.example.dkuCapstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOf9C3fq-Cc3x-uaHrhjW6mE5AG76gu1I',
    appId: '1:1037529854701:web:b72abe730eaccd37b052e4',
    messagingSenderId: '1037529854701',
    projectId: 'fcm1-e8c54',
    authDomain: 'fcm1-e8c54.firebaseapp.com',
    storageBucket: 'fcm1-e8c54.appspot.com',
    measurementId: 'G-V7M8RS3PFF',
  );

}